services:
  - type: web
    name: attacksim-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 --timeout 120 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_CONFIG  
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SECURITY_PASSWORD_SALT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: attacksim-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://discord-clone-yourproject.vercel.app

databases:
  - name: attacksim-db
    databaseName: attacksim
    user: attacksim
    plan: free 