services:
  - type: web
    name: attacksim-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r ./requirements.txt
    startCommand: gunicorn -w 4 --timeout 120 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_CONFIG  
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SECURITY_PASSWORD_SALT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: attacksim-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://discord-clone-tau-smoky.vercel.app
      
      # Gmail Email Configuration
      - key: MAIL_USERNAME
        value: it.help.service.alerts@gmail.com
      - key: MAIL_PASSWORD
        value: epxuhfoclclpfykn
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: ADMIN_EMAIL
        value: it.help.service.alerts@gmail.com

databases:
  - name: attacksim-db
    databaseName: attacksim
    user: attacksim
    plan: free 